(require '[clojure.string :as str])
(require '[clojure.set :as set])

(->> (slurp "input")
     (#(str/split % #"\n"))
     (map #(seq (char-array %)))
     (map #(split-at (/ (count %) 2) %))
     (map #(map set %))
     (map #(apply set/intersection %))
     (map seq)
     (flatten)
     (map int)
     (#(for [x %] (if (< x 91) (+ (- x 65) 27) (- x 96))))
     (reduce +))
